// <auto-generated />
using System;
using GameServer.Utils;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameServer.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20250930184929_SimplifyAccountLinking")]
    partial class SimplifyAccountLinking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GameServer.Models.PlayerData.ActivityEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AllusionId")
                        .HasColumnType("int");

                    b.Property<string>("AllusionType")
                        .HasColumnType("longtext");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageMD5")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageURL")
                        .HasColumnType("longtext");

                    b.Property<int>("List")
                        .HasColumnType("int");

                    b.Property<int>("PlayerCreationId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .HasColumnType("longtext");

                    b.Property<string>("Tags")
                        .HasColumnType("longtext");

                    b.Property<string>("Topic")
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ActivityLog");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.AnnouncementData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("longtext");

                    b.Property<int>("Platform")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .HasColumnType("longtext");

                    b.Property<string>("Text")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.AwardUnlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("AwardUnlocks");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.GriefReportData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BadRectBottom")
                        .HasColumnType("longtext");

                    b.Property<string>("BadRectTop")
                        .HasColumnType("longtext");

                    b.Property<string>("Comments")
                        .HasColumnType("longtext");

                    b.Property<string>("Context")
                        .HasColumnType("longtext");

                    b.Property<string>("Reason")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("GriefReports");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.HeartedProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("HeartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("HeartedUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsMNR")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HeartedUserId");

                    b.HasIndex("UserId");

                    b.ToTable("HeartedProfiles");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.MailMessageData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachmentReference")
                        .HasColumnType("longtext");

                    b.Property<string>("Body")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("HasForwarded")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("HasRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("HasReplied")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("RecipientId")
                        .HasColumnType("int");

                    b.Property<string>("RecipientList")
                        .HasColumnType("longtext");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.HasIndex("SenderId");

                    b.ToTable("MailMessages");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.Moderator", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Moderators");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.POIVisit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("PointOfInterestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("POIVisits");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCommentData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Platform")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerComments");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCommentRatingData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PlayerCommentId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerCommentId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerCommentRatings");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerComplaintData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasColumnType("longtext");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Reason")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("UserId");

                    b.ToTable("PlayerComplaints");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreationComplaintData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasColumnType("longtext");

                    b.Property<int>("PlayerCreationId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Reason")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerCreationId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("UserId");

                    b.ToTable("PlayerCreationComplaints");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.HeartedPlayerCreation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("HeartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("HeartedPlayerCreationId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HeartedPlayerCreationId");

                    b.HasIndex("UserId");

                    b.ToTable("HeartedPlayerCreations");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationBookmark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookmarkedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("BookmarkedPlayerCreationId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookmarkedPlayerCreationId");

                    b.HasIndex("UserId");

                    b.ToTable("PlayerCreationBookmarks");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationCommentData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Platform")
                        .HasColumnType("int");

                    b.Property<int>("PlayerCreationId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerCreationId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerCreationComments");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationCommentRatingData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PlayerCreationCommentId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerCreationCommentId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerCreationCommentRatings");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationData", b =>
                {
                    b.Property<int>("PlayerCreationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PlayerCreationId"));

                    b.Property<bool>("AI")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("AssociatedCoordinates")
                        .HasColumnType("longtext");

                    b.Property<string>("AssociatedItemIds")
                        .HasColumnType("longtext");

                    b.Property<string>("AssociatedUsernames")
                        .HasColumnType("longtext");

                    b.Property<bool>("AutoReset")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("AutoTags")
                        .HasColumnType("longtext");

                    b.Property<bool>("BattleFriendlyFire")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("BattleKillCount")
                        .HasColumnType("int");

                    b.Property<int>("BattleTimeLimit")
                        .HasColumnType("int");

                    b.Property<float>("BestLapTime")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DLCKeys")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<DateTime>("FirstPublished")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("HasPreview")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsMNR")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRemixable")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsTeamPick")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastPublished")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LevelMode")
                        .HasColumnType("int");

                    b.Property<float>("LongestDrift")
                        .HasColumnType("float");

                    b.Property<float>("LongestHangTime")
                        .HasColumnType("float");

                    b.Property<int>("MaxHumans")
                        .HasColumnType("int");

                    b.Property<int>("ModerationStatus")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("NumLaps")
                        .HasColumnType("int");

                    b.Property<int>("NumRacers")
                        .HasColumnType("int");

                    b.Property<int>("OriginalPlayerId")
                        .HasColumnType("int");

                    b.Property<int>("ParentCreationId")
                        .HasColumnType("int");

                    b.Property<int>("ParentPlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Platform")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("RaceType")
                        .HasColumnType("int");

                    b.Property<int>("RacesFinished")
                        .HasColumnType("int");

                    b.Property<int>("RacesWon")
                        .HasColumnType("int");

                    b.Property<bool>("RequiresDLC")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ScoreboardMode")
                        .HasColumnType("int");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .HasColumnType("longtext");

                    b.Property<int>("TrackId")
                        .HasColumnType("int");

                    b.Property<int>("TrackTheme")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserTags")
                        .HasColumnType("longtext");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<string>("WeaponSet")
                        .HasColumnType("longtext");

                    b.HasKey("PlayerCreationId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerCreations");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationDownload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DownloadedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PlayerCreationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerCreationId");

                    b.ToTable("PlayerCreationDownloads");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Platform")
                        .HasColumnType("int");

                    b.Property<int>("PlayerCreationId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerCreationId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerCreationPoints");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationRaceStarted", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PlayerCreationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerCreationId");

                    b.ToTable("PlayerCreationRacesStarted");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationRatingData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<int>("PlayerCreationId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerCreationId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerCreationRatings");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PlayerCreationId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerCreationId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerCreationReviews");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationReviewRatingData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PlayerCreationReviewId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerCreationReviewId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerCreationReviewRatings");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationUniqueRacer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PlayerCreationId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerCreationId");

                    b.ToTable("PlayerCreationUniqueRacers");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationView", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PlayerCreationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ViewedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerCreationId");

                    b.ToTable("PlayerCreationViews");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerExperiencePoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerExperiencePoints");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerPoints");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerRatingData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerRatings");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.RaceFinished", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FinishedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsWinner")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("OnlineRacesFinished");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.RaceStarted", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("OnlineRacesStarted");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.Score", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("BestLapTime")
                        .HasColumnType("float");

                    b.Property<int>("CharacterIdx")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("FinishTime")
                        .HasColumnType("float");

                    b.Property<string>("GhostCarDataMD5")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsMNR")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("KartIdx")
                        .HasColumnType("int");

                    b.Property<float>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("LocationTag")
                        .HasColumnType("longtext");

                    b.Property<float>("Longitude")
                        .HasColumnType("float");

                    b.Property<int>("Platform")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("PlaygroupSize")
                        .HasColumnType("int");

                    b.Property<float>("Points")
                        .HasColumnType("float");

                    b.Property<int>("SubGroupId")
                        .HasColumnType("int");

                    b.Property<int>("SubKeyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SubKeyId");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.TravelPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("TravelPoints");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<bool>("AllowOppositePlatform")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("CharacterIdx")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("HasCheckedInBefore")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("KartIdx")
                        .HasColumnType("int");

                    b.Property<float>("LastLatitude")
                        .HasColumnType("float");

                    b.Property<float>("LastLongitude")
                        .HasColumnType("float");

                    b.Property<float>("LongestDrift")
                        .HasColumnType("float");

                    b.Property<float>("LongestHangTime")
                        .HasColumnType("float");

                    b.Property<int>("LongestWinStreak")
                        .HasColumnType("int");

                    b.Property<float>("ModMiles")
                        .HasColumnType("float");

                    b.Property<int>("OnlineDisconnected")
                        .HasColumnType("int");

                    b.Property<int>("OnlineForfeit")
                        .HasColumnType("int");

                    b.Property<ulong>("PSNID")
                        .HasColumnType("bigint unsigned");

                    b.Property<bool>("PlayedMNR")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PolicyAccepted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Quota")
                        .HasColumnType("int");

                    b.Property<string>("Quote")
                        .HasColumnType("longtext");

                    b.Property<ulong>("RPCNID")
                        .HasColumnType("bigint unsigned");

                    b.Property<bool>("ShowCreationsWithoutPreviews")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.Property<int>("WinStreak")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.AwardUnlock", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.User", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.GriefReportData", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.HeartedProfile", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.User", "HeartedUser")
                        .WithMany("HeartedByProfiles")
                        .HasForeignKey("HeartedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameServer.Models.PlayerData.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HeartedUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.MailMessageData", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.User", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameServer.Models.PlayerData.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipient");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.POIVisit", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.User", "Player")
                        .WithMany("POIVisits")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCommentData", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameServer.Models.PlayerData.User", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCommentRatingData", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.PlayerCommentData", "Comment")
                        .WithMany("CommentRating")
                        .HasForeignKey("PlayerCommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameServer.Models.PlayerData.User", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerComplaintData", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.User", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameServer.Models.PlayerData.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreationComplaintData", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationData", "PlayerCreation")
                        .WithMany()
                        .HasForeignKey("PlayerCreationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameServer.Models.PlayerData.User", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameServer.Models.PlayerData.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("PlayerCreation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.HeartedPlayerCreation", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationData", "HeartedCreation")
                        .WithMany("Hearts")
                        .HasForeignKey("HeartedPlayerCreationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameServer.Models.PlayerData.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HeartedCreation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationBookmark", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationData", "BookmarkedCreation")
                        .WithMany("Bookmarks")
                        .HasForeignKey("BookmarkedPlayerCreationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameServer.Models.PlayerData.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookmarkedCreation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationCommentData", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationData", "Creation")
                        .WithMany("Comments")
                        .HasForeignKey("PlayerCreationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameServer.Models.PlayerData.User", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creation");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationCommentRatingData", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationCommentData", "Comment")
                        .WithMany("CommentRatings")
                        .HasForeignKey("PlayerCreationCommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameServer.Models.PlayerData.User", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationData", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.User", "Author")
                        .WithMany("PlayerCreations")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationDownload", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationData", "Creation")
                        .WithMany("Downloads")
                        .HasForeignKey("PlayerCreationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creation");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationPoint", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationData", "Creation")
                        .WithMany("Points")
                        .HasForeignKey("PlayerCreationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameServer.Models.PlayerData.User", "Player")
                        .WithMany("PlayerCreationPoints")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creation");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationRaceStarted", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationData", "Creation")
                        .WithMany("RacesStarted")
                        .HasForeignKey("PlayerCreationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creation");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationRatingData", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationData", "Creation")
                        .WithMany("Ratings")
                        .HasForeignKey("PlayerCreationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameServer.Models.PlayerData.User", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creation");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationReview", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationData", "Creation")
                        .WithMany("Reviews")
                        .HasForeignKey("PlayerCreationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameServer.Models.PlayerData.User", "User")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationReviewRatingData", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationReview", "Review")
                        .WithMany("ReviewRatings")
                        .HasForeignKey("PlayerCreationReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameServer.Models.PlayerData.User", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationUniqueRacer", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationData", "Creation")
                        .WithMany("UniqueRacers")
                        .HasForeignKey("PlayerCreationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creation");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationView", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationData", "Creation")
                        .WithMany("Views")
                        .HasForeignKey("PlayerCreationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creation");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerExperiencePoint", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.User", "Player")
                        .WithMany("PlayerExperiencePoints")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerPoint", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.User", "Player")
                        .WithMany("PlayerPoints")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerRatingData", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameServer.Models.PlayerData.User", "Player")
                        .WithMany("PlayerRatings")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.RaceFinished", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.User", "Player")
                        .WithMany("RacesFinished")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.RaceStarted", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.User", "Player")
                        .WithMany("RacesStarted")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.Score", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.User", "User")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationData", "Creation")
                        .WithMany("Scores")
                        .HasForeignKey("SubKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.TravelPoint", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.User", "Player")
                        .WithMany("TravelPointsData")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCommentData", b =>
                {
                    b.Navigation("CommentRating");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationCommentData", b =>
                {
                    b.Navigation("CommentRatings");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationData", b =>
                {
                    b.Navigation("Bookmarks");

                    b.Navigation("Comments");

                    b.Navigation("Downloads");

                    b.Navigation("Hearts");

                    b.Navigation("Points");

                    b.Navigation("RacesStarted");

                    b.Navigation("Ratings");

                    b.Navigation("Reviews");

                    b.Navigation("Scores");

                    b.Navigation("UniqueRacers");

                    b.Navigation("Views");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationReview", b =>
                {
                    b.Navigation("ReviewRatings");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.User", b =>
                {
                    b.Navigation("HeartedByProfiles");

                    b.Navigation("POIVisits");

                    b.Navigation("PlayerCreationPoints");

                    b.Navigation("PlayerCreations");

                    b.Navigation("PlayerExperiencePoints");

                    b.Navigation("PlayerPoints");

                    b.Navigation("PlayerRatings");

                    b.Navigation("RacesFinished");

                    b.Navigation("RacesStarted");

                    b.Navigation("TravelPointsData");
                });
#pragma warning restore 612, 618
        }
    }
}
