// <auto-generated />
using System;
using GameServer.Utils;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameServer.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20260923075317_DatabaseRewrite")]
    partial class DatabaseRewrite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GameServer.Models.PlayerData.ActivityEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AllusionId")
                        .HasColumnType("int");

                    b.Property<string>("AllusionType")
                        .HasColumnType("longtext");

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("CreatedAt"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageMD5")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageURL")
                        .HasColumnType("longtext");

                    b.Property<int>("List")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerCreationId")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .HasColumnType("longtext");

                    b.Property<string>("Tags")
                        .HasColumnType("longtext");

                    b.Property<string>("Topic")
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PlayerCreationId");

                    b.HasIndex("PlayerId");

                    b.ToTable("ActivityLog");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.Analytics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("CreatedAt"));

                    b.Property<string>("Data")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Analytics");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.AnnouncementData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("CreatedAt"));

                    b.Property<string>("LanguageCode")
                        .HasColumnType("longtext");

                    b.Property<int>("Platform")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .HasColumnType("longtext");

                    b.Property<string>("Text")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.AwardUnlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("AwardUnlocks");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.BlockedUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlockedUserId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BlockedUserId");

                    b.HasIndex("UserId");

                    b.ToTable("BlockedUsers");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.Buddy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuddyUserId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuddyUserId");

                    b.HasIndex("UserId");

                    b.ToTable("Buddies");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.GriefReportData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BadRectBottom")
                        .HasColumnType("longtext");

                    b.Property<string>("BadRectTop")
                        .HasColumnType("longtext");

                    b.Property<string>("Comments")
                        .HasColumnType("longtext");

                    b.Property<string>("Context")
                        .HasColumnType("longtext");

                    b.Property<string>("Reason")
                        .HasColumnType("longtext");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("GriefReports");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.HeartedProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("HeartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("HeartedAt"));

                    b.Property<int>("HeartedUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsMNR")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HeartedUserId");

                    b.HasIndex("UserId");

                    b.ToTable("HeartedProfiles");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.MailMessageData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachmentReference")
                        .HasColumnType("longtext");

                    b.Property<string>("Body")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("CreatedAt"));

                    b.Property<bool>("HasForwarded")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("HasRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("HasReplied")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("RecipientId")
                        .HasColumnType("int");

                    b.Property<string>("RecipientList")
                        .HasColumnType("longtext");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.HasIndex("SenderId");

                    b.ToTable("MailMessages");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.Moderator", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("BanUsers")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ChangeCreationStatus")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ChangeUserQuota")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ChangeUserSettings")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ManageAnnouncements")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ManageBannedConsoleIDs")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ManageBannedIPs")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ManageHotlap")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ManageModerators")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ManageSystemEvents")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ManageTeamPicks")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ManageUserSessions")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ManageWhitelist")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<bool>("RemovePlayerCreationComments")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RemovePlayerCreations")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RemoveProfileAvatars")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RemoveProfileComments")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RemoveScores")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RemoveUsers")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ResetCreationStats")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ResetUserStats")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.Property<bool>("ViewGriefReports")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ViewPlayerComplaints")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ViewPlayerCreationComplaints")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("ID");

                    b.ToTable("Moderators");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.ModeratorAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("GriefReportId")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerComplaintId")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerCreationComplaintId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GriefReportId");

                    b.HasIndex("PlayerComplaintId");

                    b.HasIndex("PlayerCreationComplaintId");

                    b.HasIndex("UserId");

                    b.ToTable("ModeratorAssignments");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.ModeratorSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastTokenRefresh")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("char(36)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ModeratorSessions");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.POIVisit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("PointOfInterestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("POIVisits");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCommentData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("CreatedAt"));

                    b.Property<int>("Platform")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerComments");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCommentRatingData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PlayerCommentId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("RatedAt"));

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerCommentId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerCommentRatings");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerComplaintData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasColumnType("longtext");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Reason")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("UserId");

                    b.ToTable("PlayerComplaints");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreationComplaintData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasColumnType("longtext");

                    b.Property<int>("PlayerCreationId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Reason")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerCreationId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("UserId");

                    b.ToTable("PlayerCreationComplaints");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.HeartedPlayerCreation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("HeartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("HeartedPlayerCreationId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HeartedPlayerCreationId");

                    b.HasIndex("UserId");

                    b.ToTable("HeartedPlayerCreations");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationBookmark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookmarkedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("BookmarkedAt"));

                    b.Property<int>("BookmarkedPlayerCreationId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookmarkedPlayerCreationId");

                    b.HasIndex("UserId");

                    b.ToTable("PlayerCreationBookmarks");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationCommentData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("CreatedAt"));

                    b.Property<int>("Platform")
                        .HasColumnType("int");

                    b.Property<int>("PlayerCreationId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.HasKey("Id");

                    b.HasIndex("PlayerCreationId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerCreationComments");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationCommentRatingData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PlayerCreationCommentId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("RatedAt"));

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerCreationCommentId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerCreationCommentRatings");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationData", b =>
                {
                    b.Property<int>("PlayerCreationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PlayerCreationId"));

                    b.Property<bool>("AI")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("AssociatedCoordinates")
                        .HasColumnType("longtext");

                    b.Property<string>("AssociatedItemIds")
                        .HasColumnType("longtext");

                    b.Property<string>("AssociatedUsernames")
                        .HasColumnType("longtext");

                    b.Property<bool>("AutoReset")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("AutoTags")
                        .HasColumnType("longtext");

                    b.Property<bool>("BattleFriendlyFire")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("BattleKillCount")
                        .HasColumnType("int");

                    b.Property<int>("BattleTimeLimit")
                        .HasColumnType("int");

                    b.Property<float>("BestLapTime")
                        .HasColumnType("float");

                    b.Property<float>("Coolness")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("CreatedAt"));

                    b.Property<string>("DLCKeys")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<int>("Downloads")
                        .HasColumnType("int");

                    b.Property<int>("DownloadsLastWeek")
                        .HasColumnType("int");

                    b.Property<int>("DownloadsThisWeek")
                        .HasColumnType("int");

                    b.Property<DateTime>("FirstPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("FirstPublished"));

                    b.Property<bool>("HasPreview")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<int>("Hearts")
                        .HasColumnType("int");

                    b.Property<int>("HeartsThisMonth")
                        .HasColumnType("int");

                    b.Property<int>("HeartsThisWeek")
                        .HasColumnType("int");

                    b.Property<bool>("IsMNR")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRemixable")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsTeamPick")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastPublished")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LevelMode")
                        .HasColumnType("int");

                    b.Property<float>("LongestDrift")
                        .HasColumnType("float");

                    b.Property<float>("LongestHangTime")
                        .HasColumnType("float");

                    b.Property<int>("MaxHumans")
                        .HasColumnType("int");

                    b.Property<int>("ModerationStatus")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("NumLaps")
                        .HasColumnType("int");

                    b.Property<int>("NumRacers")
                        .HasColumnType("int");

                    b.Property<int>("OriginalPlayerId")
                        .HasColumnType("int");

                    b.Property<int>("ParentCreationId")
                        .HasColumnType("int");

                    b.Property<int>("ParentPlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Platform")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<float>("Points")
                        .HasColumnType("float");

                    b.Property<float>("PointsLastWeek")
                        .HasColumnType("float");

                    b.Property<float>("PointsThisWeek")
                        .HasColumnType("float");

                    b.Property<float>("PointsToday")
                        .HasColumnType("float");

                    b.Property<float>("PointsYesterday")
                        .HasColumnType("float");

                    b.Property<int>("RaceType")
                        .HasColumnType("int");

                    b.Property<int>("RacesFinished")
                        .HasColumnType("int");

                    b.Property<int>("RacesStarted")
                        .HasColumnType("int");

                    b.Property<int>("RacesStartedThisMonth")
                        .HasColumnType("int");

                    b.Property<int>("RacesStartedThisWeek")
                        .HasColumnType("int");

                    b.Property<int>("RacesWon")
                        .HasColumnType("int");

                    b.Property<float>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("RatingDown")
                        .HasColumnType("int");

                    b.Property<int>("RatingUp")
                        .HasColumnType("int");

                    b.Property<int>("RatingUpThisMonth")
                        .HasColumnType("int");

                    b.Property<int>("RatingUpThisWeek")
                        .HasColumnType("int");

                    b.Property<bool>("RequiresDLC")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ScoreboardMode")
                        .HasColumnType("int");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .HasColumnType("longtext");

                    b.Property<int>("TrackId")
                        .HasColumnType("int");

                    b.Property<int>("TrackTheme")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UniqueRacers")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.Property<string>("UserTags")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<int>("Views")
                        .HasColumnType("int");

                    b.Property<int>("ViewsLastWeek")
                        .HasColumnType("int");

                    b.Property<int>("ViewsThisWeek")
                        .HasColumnType("int");

                    b.Property<int>("Votes")
                        .HasColumnType("int");

                    b.Property<string>("WeaponSet")
                        .HasColumnType("longtext");

                    b.HasKey("PlayerCreationId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerCreations");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationDownload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DownloadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("DownloadedAt"));

                    b.Property<int>("PlayerCreationId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerCreationId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerCreationDownloads");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("CreatedAt"));

                    b.Property<int>("Platform")
                        .HasColumnType("int");

                    b.Property<int>("PlayerCreationId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerCreationId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerCreationPoints");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationRaceStarted", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PlayerCreationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("StartedAt"));

                    b.HasKey("Id");

                    b.HasIndex("PlayerCreationId");

                    b.ToTable("PlayerCreationRacesStarted");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationRatingData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<int>("PlayerCreationId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("RatedAt"));

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerCreationId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerCreationRatings");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("CreatedAt"));

                    b.Property<int>("PlayerCreationId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.HasKey("Id");

                    b.HasIndex("PlayerCreationId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerCreationReviews");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationReviewRatingData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PlayerCreationReviewId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("RatedAt"));

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerCreationReviewId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerCreationReviewRatings");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationUniqueRacer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PlayerCreationId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerCreationId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerCreationUniqueRacers");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationView", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PlayerCreationId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ViewedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("ViewedAt"));

                    b.HasKey("Id");

                    b.HasIndex("PlayerCreationId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerCreationViews");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerExperiencePoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("CreatedAt"));

                    b.Property<int>("Platform")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerExperiencePoints");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("CreatedAt"));

                    b.Property<int>("Platform")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerPoints");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerRatingData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("RatedAt"));

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerRatings");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.RaceFinished", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FinishedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("FinishedAt"));

                    b.Property<bool>("IsWinner")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("OnlineRacesFinished");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.RaceStarted", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("StartedAt"));

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("OnlineRacesStarted");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.Score", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("BestLapTime")
                        .HasColumnType("float");

                    b.Property<int>("CharacterIdx")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("FinishTime")
                        .HasColumnType("float");

                    b.Property<string>("GhostCarDataMD5")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsMNR")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("KartIdx")
                        .HasColumnType("int");

                    b.Property<float>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("LocationTag")
                        .HasColumnType("longtext");

                    b.Property<float>("Longitude")
                        .HasColumnType("float");

                    b.Property<int>("Platform")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("PlaygroupSize")
                        .HasColumnType("int");

                    b.Property<float>("Points")
                        .HasColumnType("float");

                    b.Property<int>("SubGroupId")
                        .HasColumnType("int");

                    b.Property<int>("SubKeyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SubKeyId");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.SessionData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConsoleId")
                        .HasColumnType("longtext");

                    b.Property<string>("IpAddress")
                        .HasColumnType("varchar(45)");

                    b.Property<bool>("IsMNR")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRpcn")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastPing")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("LastPing"));

                    b.Property<int>("Platform")
                        .HasColumnType("int");

                    b.Property<int>("Presence")
                        .HasColumnType("int");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("char(36)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.TravelPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("CreatedAt"));

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("TravelPoints");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<bool>("AllowOppositePlatform")
                        .HasColumnType("tinyint(1)");

                    b.Property<float>("CharacterCreatorPointsLastWeekPS3")
                        .HasColumnType("float");

                    b.Property<float>("CharacterCreatorPointsLastWeekPSP")
                        .HasColumnType("float");

                    b.Property<float>("CharacterCreatorPointsLastWeekPSV")
                        .HasColumnType("float");

                    b.Property<float>("CharacterCreatorPointsPS3")
                        .HasColumnType("float");

                    b.Property<float>("CharacterCreatorPointsPSP")
                        .HasColumnType("float");

                    b.Property<float>("CharacterCreatorPointsPSV")
                        .HasColumnType("float");

                    b.Property<float>("CharacterCreatorPointsThisWeekPS3")
                        .HasColumnType("float");

                    b.Property<float>("CharacterCreatorPointsThisWeekPSP")
                        .HasColumnType("float");

                    b.Property<float>("CharacterCreatorPointsThisWeekPSV")
                        .HasColumnType("float");

                    b.Property<int>("CharacterIdx")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("CreatedAt"));

                    b.Property<float>("CreatorPointsLastWeekPS3")
                        .HasColumnType("float");

                    b.Property<float>("CreatorPointsLastWeekPSP")
                        .HasColumnType("float");

                    b.Property<float>("CreatorPointsLastWeekPSV")
                        .HasColumnType("float");

                    b.Property<float>("CreatorPointsPS3")
                        .HasColumnType("float");

                    b.Property<float>("CreatorPointsPSP")
                        .HasColumnType("float");

                    b.Property<float>("CreatorPointsPSV")
                        .HasColumnType("float");

                    b.Property<float>("CreatorPointsThisWeekPS3")
                        .HasColumnType("float");

                    b.Property<float>("CreatorPointsThisWeekPSP")
                        .HasColumnType("float");

                    b.Property<float>("CreatorPointsThisWeekPSV")
                        .HasColumnType("float");

                    b.Property<float>("ExperiencePointsLastWeekPS3")
                        .HasColumnType("float");

                    b.Property<float>("ExperiencePointsLastWeekPSP")
                        .HasColumnType("float");

                    b.Property<float>("ExperiencePointsLastWeekPSV")
                        .HasColumnType("float");

                    b.Property<float>("ExperiencePointsPS3")
                        .HasColumnType("float");

                    b.Property<float>("ExperiencePointsPSP")
                        .HasColumnType("float");

                    b.Property<float>("ExperiencePointsPSV")
                        .HasColumnType("float");

                    b.Property<float>("ExperiencePointsThisWeekPS3")
                        .HasColumnType("float");

                    b.Property<float>("ExperiencePointsThisWeekPSP")
                        .HasColumnType("float");

                    b.Property<float>("ExperiencePointsThisWeekPSV")
                        .HasColumnType("float");

                    b.Property<bool>("HasCheckedInBefore")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("tinyint(1)");

                    b.Property<float>("KartCreatorPointsLastWeekPS3")
                        .HasColumnType("float");

                    b.Property<float>("KartCreatorPointsLastWeekPSP")
                        .HasColumnType("float");

                    b.Property<float>("KartCreatorPointsLastWeekPSV")
                        .HasColumnType("float");

                    b.Property<float>("KartCreatorPointsPS3")
                        .HasColumnType("float");

                    b.Property<float>("KartCreatorPointsPSP")
                        .HasColumnType("float");

                    b.Property<float>("KartCreatorPointsPSV")
                        .HasColumnType("float");

                    b.Property<float>("KartCreatorPointsThisWeekPS3")
                        .HasColumnType("float");

                    b.Property<float>("KartCreatorPointsThisWeekPSP")
                        .HasColumnType("float");

                    b.Property<float>("KartCreatorPointsThisWeekPSV")
                        .HasColumnType("float");

                    b.Property<int>("KartIdx")
                        .HasColumnType("int");

                    b.Property<float>("LastLatitude")
                        .HasColumnType("float");

                    b.Property<float>("LastLongitude")
                        .HasColumnType("float");

                    b.Property<float>("LongestDrift")
                        .HasColumnType("float");

                    b.Property<float>("LongestHangTime")
                        .HasColumnType("float");

                    b.Property<int>("LongestWinStreak")
                        .HasColumnType("int");

                    b.Property<float>("ModMiles")
                        .HasColumnType("float");

                    b.Property<int>("OnlineDisconnected")
                        .HasColumnType("int");

                    b.Property<int>("OnlineFinished")
                        .HasColumnType("int");

                    b.Property<int>("OnlineFinishedLastWeek")
                        .HasColumnType("int");

                    b.Property<int>("OnlineFinishedThisWeek")
                        .HasColumnType("int");

                    b.Property<int>("OnlineForfeit")
                        .HasColumnType("int");

                    b.Property<int>("OnlineRaces")
                        .HasColumnType("int");

                    b.Property<int>("OnlineRacesLastWeek")
                        .HasColumnType("int");

                    b.Property<int>("OnlineRacesThisWeek")
                        .HasColumnType("int");

                    b.Property<int>("OnlineWins")
                        .HasColumnType("int");

                    b.Property<int>("OnlineWinsLastWeek")
                        .HasColumnType("int");

                    b.Property<int>("OnlineWinsThisWeek")
                        .HasColumnType("int");

                    b.Property<ulong>("PSNID")
                        .HasColumnType("bigint unsigned");

                    b.Property<bool>("PlayedMNR")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PlayerCreationsPrivacy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.Property<int>("PointsLastWeekPS3")
                        .HasColumnType("int");

                    b.Property<int>("PointsLastWeekPSP")
                        .HasColumnType("int");

                    b.Property<int>("PointsLastWeekPSV")
                        .HasColumnType("int");

                    b.Property<int>("PointsPS3")
                        .HasColumnType("int");

                    b.Property<int>("PointsPSP")
                        .HasColumnType("int");

                    b.Property<int>("PointsPSV")
                        .HasColumnType("int");

                    b.Property<int>("PointsThisWeekPS3")
                        .HasColumnType("int");

                    b.Property<int>("PointsThisWeekPSP")
                        .HasColumnType("int");

                    b.Property<int>("PointsThisWeekPSV")
                        .HasColumnType("int");

                    b.Property<bool>("PolicyAccepted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ProfilePrivacy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.Property<int>("Quota")
                        .HasColumnType("int");

                    b.Property<string>("Quote")
                        .HasColumnType("longtext");

                    b.Property<ulong>("RPCNID")
                        .HasColumnType("bigint unsigned");

                    b.Property<bool>("ShowCreationsWithoutPreviews")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("TotalCharactersPS3")
                        .HasColumnType("int");

                    b.Property<int>("TotalCharactersPSP")
                        .HasColumnType("int");

                    b.Property<int>("TotalCharactersPSV")
                        .HasColumnType("int");

                    b.Property<int>("TotalKartsPS3")
                        .HasColumnType("int");

                    b.Property<int>("TotalKartsPSP")
                        .HasColumnType("int");

                    b.Property<int>("TotalKartsPSV")
                        .HasColumnType("int");

                    b.Property<int>("TotalTracksPS3")
                        .HasColumnType("int");

                    b.Property<int>("TotalTracksPSP")
                        .HasColumnType("int");

                    b.Property<int>("TotalTracksPSV")
                        .HasColumnType("int");

                    b.Property<float>("TotalXPLastWeekPS3")
                        .HasColumnType("float");

                    b.Property<float>("TotalXPLastWeekPSP")
                        .HasColumnType("float");

                    b.Property<float>("TotalXPLastWeekPSV")
                        .HasColumnType("float");

                    b.Property<float>("TotalXPPS3")
                        .HasColumnType("float");

                    b.Property<float>("TotalXPPSP")
                        .HasColumnType("float");

                    b.Property<float>("TotalXPPSV")
                        .HasColumnType("float");

                    b.Property<float>("TotalXPThisWeekPS3")
                        .HasColumnType("float");

                    b.Property<float>("TotalXPThisWeekPSP")
                        .HasColumnType("float");

                    b.Property<float>("TotalXPThisWeekPSV")
                        .HasColumnType("float");

                    b.Property<float>("TrackCreatorPointsLastWeekPS3")
                        .HasColumnType("float");

                    b.Property<float>("TrackCreatorPointsLastWeekPSP")
                        .HasColumnType("float");

                    b.Property<float>("TrackCreatorPointsLastWeekPSV")
                        .HasColumnType("float");

                    b.Property<float>("TrackCreatorPointsPS3")
                        .HasColumnType("float");

                    b.Property<float>("TrackCreatorPointsPSP")
                        .HasColumnType("float");

                    b.Property<float>("TrackCreatorPointsPSV")
                        .HasColumnType("float");

                    b.Property<float>("TrackCreatorPointsThisWeekPS3")
                        .HasColumnType("float");

                    b.Property<float>("TrackCreatorPointsThisWeekPSP")
                        .HasColumnType("float");

                    b.Property<float>("TrackCreatorPointsThisWeekPSV")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.Property<int>("WinStreak")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.ActivityEvent", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.HasOne("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationData", "PlayerCreation")
                        .WithMany("ActivityLog")
                        .HasForeignKey("PlayerCreationId");

                    b.HasOne("GameServer.Models.PlayerData.User", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");

                    b.Navigation("Author");

                    b.Navigation("Player");

                    b.Navigation("PlayerCreation");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.Analytics", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.AwardUnlock", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.User", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.BlockedUser", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.User", "BlockedPlayer")
                        .WithMany("BlockedByUsers")
                        .HasForeignKey("BlockedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameServer.Models.PlayerData.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlockedPlayer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.Buddy", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.User", "BuddyUser")
                        .WithMany("BuddiesWithUsers")
                        .HasForeignKey("BuddyUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameServer.Models.PlayerData.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuddyUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.GriefReportData", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.HeartedProfile", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.User", "HeartedUser")
                        .WithMany("HeartedByProfiles")
                        .HasForeignKey("HeartedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameServer.Models.PlayerData.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HeartedUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.MailMessageData", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.User", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameServer.Models.PlayerData.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipient");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.ModeratorAssignment", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.GriefReportData", "Report")
                        .WithMany("ModeratorAssignments")
                        .HasForeignKey("GriefReportId");

                    b.HasOne("GameServer.Models.PlayerData.PlayerComplaintData", "PlayerComplaint")
                        .WithMany("ModeratorAssignments")
                        .HasForeignKey("PlayerComplaintId");

                    b.HasOne("GameServer.Models.PlayerData.PlayerCreationComplaintData", "PlayerCreationComplaint")
                        .WithMany("ModeratorAssignments")
                        .HasForeignKey("PlayerCreationComplaintId");

                    b.HasOne("GameServer.Models.PlayerData.Moderator", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerComplaint");

                    b.Navigation("PlayerCreationComplaint");

                    b.Navigation("Report");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.ModeratorSession", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.Moderator", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.POIVisit", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.User", "Player")
                        .WithMany("POIVisits")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCommentData", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameServer.Models.PlayerData.User", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCommentRatingData", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.PlayerCommentData", "Comment")
                        .WithMany("CommentRating")
                        .HasForeignKey("PlayerCommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameServer.Models.PlayerData.User", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerComplaintData", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.User", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameServer.Models.PlayerData.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreationComplaintData", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationData", "PlayerCreation")
                        .WithMany()
                        .HasForeignKey("PlayerCreationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameServer.Models.PlayerData.User", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameServer.Models.PlayerData.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("PlayerCreation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.HeartedPlayerCreation", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationData", "HeartedCreation")
                        .WithMany("HeartsData")
                        .HasForeignKey("HeartedPlayerCreationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameServer.Models.PlayerData.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HeartedCreation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationBookmark", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationData", "BookmarkedCreation")
                        .WithMany("Bookmarks")
                        .HasForeignKey("BookmarkedPlayerCreationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameServer.Models.PlayerData.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookmarkedCreation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationCommentData", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationData", "Creation")
                        .WithMany("Comments")
                        .HasForeignKey("PlayerCreationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameServer.Models.PlayerData.User", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creation");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationCommentRatingData", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationCommentData", "Comment")
                        .WithMany("CommentRatings")
                        .HasForeignKey("PlayerCreationCommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameServer.Models.PlayerData.User", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationData", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.User", "Author")
                        .WithMany("PlayerCreations")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationDownload", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationData", "Creation")
                        .WithMany("DownloadsData")
                        .HasForeignKey("PlayerCreationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameServer.Models.PlayerData.User", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creation");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationPoint", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationData", "Creation")
                        .WithMany("PointsData")
                        .HasForeignKey("PlayerCreationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameServer.Models.PlayerData.User", "Player")
                        .WithMany("PlayerCreationPoints")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creation");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationRaceStarted", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationData", "Creation")
                        .WithMany("RacesStartedData")
                        .HasForeignKey("PlayerCreationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creation");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationRatingData", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationData", "Creation")
                        .WithMany("RatingsData")
                        .HasForeignKey("PlayerCreationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameServer.Models.PlayerData.User", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creation");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationReview", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationData", "Creation")
                        .WithMany("Reviews")
                        .HasForeignKey("PlayerCreationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameServer.Models.PlayerData.User", "User")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationReviewRatingData", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationReview", "Review")
                        .WithMany("ReviewRatings")
                        .HasForeignKey("PlayerCreationReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameServer.Models.PlayerData.User", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationUniqueRacer", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationData", "Creation")
                        .WithMany("UniqueRacersData")
                        .HasForeignKey("PlayerCreationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameServer.Models.PlayerData.User", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creation");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationView", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationData", "Creation")
                        .WithMany("ViewsData")
                        .HasForeignKey("PlayerCreationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameServer.Models.PlayerData.User", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creation");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerExperiencePoint", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.User", "Player")
                        .WithMany("PlayerExperiencePoints")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerPoint", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.User", "Player")
                        .WithMany("PlayerPoints")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerRatingData", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameServer.Models.PlayerData.User", "Player")
                        .WithMany("PlayerRatings")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.RaceFinished", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.User", "Player")
                        .WithMany("RacesFinished")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.RaceStarted", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.User", "Player")
                        .WithMany("RacesStarted")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.Score", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.User", "User")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationData", "Creation")
                        .WithMany("Scores")
                        .HasForeignKey("SubKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.SessionData", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.TravelPoint", b =>
                {
                    b.HasOne("GameServer.Models.PlayerData.User", "Player")
                        .WithMany("TravelPointsData")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.GriefReportData", b =>
                {
                    b.Navigation("ModeratorAssignments");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCommentData", b =>
                {
                    b.Navigation("CommentRating");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerComplaintData", b =>
                {
                    b.Navigation("ModeratorAssignments");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreationComplaintData", b =>
                {
                    b.Navigation("ModeratorAssignments");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationCommentData", b =>
                {
                    b.Navigation("CommentRatings");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationData", b =>
                {
                    b.Navigation("ActivityLog");

                    b.Navigation("Bookmarks");

                    b.Navigation("Comments");

                    b.Navigation("DownloadsData");

                    b.Navigation("HeartsData");

                    b.Navigation("PointsData");

                    b.Navigation("RacesStartedData");

                    b.Navigation("RatingsData");

                    b.Navigation("Reviews");

                    b.Navigation("Scores");

                    b.Navigation("UniqueRacersData");

                    b.Navigation("ViewsData");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.PlayerCreations.PlayerCreationReview", b =>
                {
                    b.Navigation("ReviewRatings");
                });

            modelBuilder.Entity("GameServer.Models.PlayerData.User", b =>
                {
                    b.Navigation("BlockedByUsers");

                    b.Navigation("BuddiesWithUsers");

                    b.Navigation("HeartedByProfiles");

                    b.Navigation("POIVisits");

                    b.Navigation("PlayerCreationPoints");

                    b.Navigation("PlayerCreations");

                    b.Navigation("PlayerExperiencePoints");

                    b.Navigation("PlayerPoints");

                    b.Navigation("PlayerRatings");

                    b.Navigation("RacesFinished");

                    b.Navigation("RacesStarted");

                    b.Navigation("TravelPointsData");
                });
#pragma warning restore 612, 618
        }
    }
}
